### ISSUE TITLE
stix.sty not found

### ISSUE THREAD

**Issue by sjsonucool** [kmaed/kmbeamer#1]
`\usepackage{stix}` isn't working!!

**Comment by kmaed** [comment]
See https://www.ctan.org/pkg/stix .  If you are using TeX Live, collection-fontsextra contains stix.

Of course, that is just an example. You can remove \usepackage{stix} from the code.

**Comment by sjsonucool** [comment]
Thank you. Lol I didn't know if it's necessary to have this package while using the DarkConsole theme.  Closing the issue now!
